services:
  web:
    build: .
    container_name: lotto_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: lotto_db
    environment:
      POSTGRES_DB: lotto_db
      POSTGRES_USER: lotto_user
      POSTGRES_PASSWORD: lotto_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lotto_user -d lotto_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: