# Generated by Django 6.0.5 on 2026-05-22 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='회차 번호')),
                ('winning_numbers', models.CharField(blank=True, max_length=100, verbose_name='당첨 번호')),
                ('bonus_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
                ('drawn_at', models.DateTimeField(blank=True, null=True, verbose_name='추첨 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '로또 회차',
                'verbose_name_plural': '로또 회차 목록',
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=100, verbose_name='구매 번호')),
                ('purchase_type', models.CharField(choices=[('manual', '수동'), ('auto', '자동')], max_length=10, verbose_name='구매 방식')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.lottoround', verbose_name='로또 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '구매 복권',
                'verbose_name_plural': '구매 복권 목록',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
